### ISSUE TITLE
New `Floorp-private-components` repository

### ISSUE THREAD

**Issue by christoph-heiss** [Floorp-Projects/Floorp-core#62]
Hi!

I'm maintaining the Floorp package for NixOS.
While updating Floorp to the newly released v11.11.0, I noticed - since it failed the build - that a new `Floorp-private-components` repository/submodule was introduced as part of this repository.

What does it contain? Is it required to build Floorp?
If (esp. the latter) is true, than I will go ahead and drop the Floorp package for the next release of NixOS, since I'm not willing and never will support proprietary software.

**Comment by CutterKnife** [comment]
Sure, it is a proprietary part of Floorp. But AFAIK it should be nothing or not used yet.

The team is working on new features for the release of Floorp 12. They will be using a different repository with a different license for some of its new features. Maybe it will be available by the time it is released.

**Comment by surapunoyousei** [comment]
We are in the process of implementing it so that it can be an open source project, but it will take time so do what you want.

I am the only maintainer of Floorp, so I need time.

**Comment by stefanwimmer128** [comment]
I maintain [my own personal fork of Floorp](https://codeberg.org/stefanwimmer128/floorp128), since I'm adding various patches. Is there a way for me to include these private components?

**Comment by christoph-heiss** [comment]
> Sure, it is a proprietary part of Floorp. But AFAIK it should be nothing or not used yet.

Well, than Floorp should to be explicitly marked as proprietary, so users know what they are downloading.
If you do not see the issue & impact of this - that's fine, it is your project after all.

But this change effectively prevents **anyone** from building Floorp. Be it in an automated fashion in distro packaging or individual users like @stefanwimmer128.
Simply due to the *forced* dependency via a git submodule on this proprietary compontent - which means this repository (which is needed for building of course) **cannot be checked out anymore**.

In any case, you have shattered my trust and further my willingness to package this for NixOS, other than it being literally impossible now. All users of Floorp on NixOS (of which there are definitely a few) **cannot receive updates for Floorp anymore**.
Please understand the impact of this.

I'll go ahead and deprecate the package for NixOS and hopefully be able to drop this with the upcoming release.

**Comment by stefanwimmer128** [comment]
Well 1. you can definitely still build it without the proprietary components. The AUR-floorp package, the firedragon-fork and my fork do work without those components, those features are just missing, but the browser works.

But 2. I can at least ask.

**Comment by CutterKnife** [comment]
As already mentioned, this is not permanent. It will be open source at the time of release.

Due to the rude behavior of one project that is forking Floorp, we have been forced to make changes to protect some of our assets. This means that some file structures will change, but we assure you that the parts included in the actual Floorp will continue to be open source.

**Comment by surapunoyousei** [comment]
> > Sure, it is a proprietary part of Floorp. But AFAIK it should be nothing or not used yet.
> 
> Well, than Floorp should to be explicitly marked as proprietary, so users know what they are downloading. If you do not see the issue & impact of this - that's fine, it is your project after all.
> 
> But this change effectively prevents **anyone** from building Floorp. Be it in an automated fashion in distro packaging or individual users like @stefanwimmer128. Simply due to the _forced_ dependency via a git submodule on this proprietary compontent - which means this repository (which is needed for building of course) **cannot be checked out anymore**.
> 
> In any case, you have shattered my trust and further my willingness to package this for NixOS, other than it being literally impossible now. All users of Floorp on NixOS (of which there are definitely a few) **cannot receive updates for Floorp anymore**. Please understand the impact of this.
> 
> I'll go ahead and deprecate the package for NixOS and hopefully be able to drop this with the upcoming release.

I recommend that it be removed.

We have addressed this by granting access to maintainers such as FireDragon, but if you are an open source project, you may want to turn it off.

I respect your decision.

**Comment by surapunoyousei** [comment]
> I maintain [my own personal fork of Floorp](https://codeberg.org/stefanwimmer128/floorp128), since I'm adding various patches. Is there a way for me to include these private components?

Add permission to you.

**Comment by dominichayesferen** [comment]
Aftermath context for those who may end up in here: 
https://blog.ablaze.one/4125/2024-03-11/

https://github.com/Floorp-Projects/Floorp-private-core
