### ISSUE TITLE
Upstream your changes to Mozilla

### ISSUE THREAD

**Issue by Movisivi** [Floorp-Projects/Floorp-core#65]
I find it's pretty silly that Mozilla and both Floorp are working on vertical tabs. Floorp has already done most of the heavy lifting, all Mozilla would need to do is fix it up a bit. All the Floorp developer needs to do is open up a Bugzilla ticket and upstream their features like verticals and SSBs/PWAs so all Firefox users can benefit.   I don't want to use a fork that staggers security updates.

**Comment by TheChilledBuffalo** [comment]
What makes you think Floorp staggers security updates? 🤔

It's regularly updated with security patches from upstream, sometimes receiving those patches even before Firefox users.

**Comment by Movisivi** [comment]
That's what you choose to focus on instead of that main reason the issue was opened? Please leave if you're not the maintainer or developer of the project

**Comment by TheChilledBuffalo** [comment]
As you might have already figured out, I'm indeed not the maintainer of this project. Hence, I can't comment on the "main" point of this discussion. But the security updates part, you have to admit, was a part of your original post, however "minor" it may be. I can only comment on what I know about. 

And, if you are not already aware, this is a public space and its not you who would decide if a person should stay or leave a discussion.

**Comment by TheChilledBuffalo** [comment]
Sorry that was an accident

**Comment by Movisivi** [comment]
@surapunoyousei care to comment?

**Comment by Movisivi** [comment]
> As you might have already figured out, I'm indeed not the maintainer of this project. Hence, I can't comment on the "main" point of this discussion. But the security updates part, you have to admit, was a part of your original post, however "minor" it may be. I can only comment on what I know about.

It was a part of my post but it is really obviously not the main point of it. In fact if you look at that edit history, you'll see my original post didn't even have that in there. So thanks, you added nothing to this conversation. You just wanted to hear yourself talk.

> And, if you are not already aware, this is a public space and its not you who would decide if a person should stay or leave a discussion.

And this is my thread so fuck off. 

@surapunoyousei are these the kinda jokers you align yourself with? I'll just fork your project and work with Mozilla myself.

**Comment by mkosmo** [comment]
> I don't want to use a fork that staggers security updates.

Then don't use it?

It's generally not a very good idea to discourage multiple different approaches to the same problem.  The fact that different groups try to do the same thing different ways is how we come up with even better solutions - more collective knowledge and experience is attained.

**Comment by RayKV423** [comment]
> That's not the point of my report. Please leave if you're not the maintainer or developer of the project

Wowwwwww is this the way you behave? Yikes, my dude, you need to get your head checked out. Imagine randomly insulting and horribly hostile to people for no reason. 

Makes me wonder what skeletons in your closet have. Hopefully everyone you know avoids you. I feel bad for anyone who has to deal with you. This isn’t elementary school anymore, buddy.

**Comment by surapunoyousei** [comment]
You cannot push code to Mozilla unless you have my permission to do so.

Floorp code is not recommended because it does not follow Mozilla's coding style, but I give you permission here and now.

It should be clearly stated that the line sensor is Floorp, in line with MPL2.0.

**Comment by Movisivi** [comment]
I was going to use your code regardless of whether I had your permission. What are you gonna do, sue me? Lmfao. I'll let Mozilla deal with the styling.

**Comment by Movisivi** [comment]
> > That's not the point of my report. Please leave if you're not the maintainer or developer of the project
> 
> Wowwwwww is this the way you behave? Yikes, my dude, you need to get your head checked out. Imagine randomly insulting and horribly hostile to people for no reason.
> 
> Makes me wonder what skeletons in your closet have. Hopefully everyone you know avoids you. I feel bad for anyone who has to deal with you. This isn’t elementary school anymore, buddy.

If this is what you consider hostile and insulting then how about I give you something to actually whine about you dumb cunt. I was being as calm and collected as could be. I didn't want to hear from anyone besides the developer of this project and I got it. So shut the hell up, this thread is closed, you're just spamming my inbox.

**Comment by TheChilledBuffalo** [comment]
> calm and collected as could be

Wow ok, that's a bold claim. Try recollecting what you had said in the comment that has now been removed by GitHub.

> I didn't want to hear from anyone besides the developer of this project

You never mentioned that in your original post. And even if you did, that's not how this works.

> you're just spamming my inbox

Nobody cares about *your* inbox, mate

**Comment by Movisivi** [comment]
Bunch of retards here. Thanks for providing entertainment and adding a new entry to the list of discontinued web browsers on Wikipedia in the future.
